### ISSUE TITLE
parameter problem

### ISSUE THREAD

**Issue by zhuzhuzhuxin** [airaria/AdversarialAttackInceptionV3#1]
parser.add_argument('-b',"--batch_size",default=32,type=int)
When default=32, program is running wrong.
 'predictedIds' value is:
[array([306, 244, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112,
       112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112, 112,
       112, 112, 112, 112, 112, 112]), array([[[  5.39944973e-04,   4.19075775e-04,   2.75288895e-03, ...,
           6.54422445e-04,   7.28798856e-04,   3.08565708e-04],
        [  2.13847889e-04,   1.14776101e-03,   4.00428148e-03, ...,
           1.46247132e-03,   1.22723263e-03,   1.12726865e-03],
        [  1.34383375e-03,   1.96148548e-03,   5.24227647e-03, ...,
           1.78150367e-03,   3.35320504e-03,   1.48972846e-03],
        ..., 
        [  1.16277591e-03,   2.70989304e-03,   2.69153970e-03, ...,
When default=1, the program is operating normally.So,I want to know why are you set the 'default' value is 32?

**Comment by airaria** [comment]
Thanks for your feedback.
The bug has been fixed.

**Comment by zhuzhuzhuxin** [comment]
@airaria You are welcome! Could you please send the paper to me?

**Comment by airaria** [comment]
Sorry but which paper do you mean?





At 2017-11-21 10:43:31, "zhuzhuzhuxin" <notifications@github.com> wrote:


@airaria You are welcome! Could you please send the paper to me?

**Comment by zhuzhuzhuxin** [comment]
@airaria The paper about this code.

**Comment by airaria** [comment]
@zhuzhuzhuxin 
https://arxiv.org/abs/1611.02770
https://arxiv.org/abs/1608.04644

**Comment by zhuzhuzhuxin** [comment]
@airaria Thank you very much!
